language: ruby
rvm:
- 2.3.3
script: bundle exec jekyll build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: ljn.io
  local-dir: _site/
  skip_cleanup: true
  region: eu-west-1
  on:
    branch: master
after_deploy:
  - aws configure set preview.cloudfront true
  - test $TRAVIS_BRANCH = "master" && aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
  
