
title: Linus Norton
email: linusnorton@gmail.com
description: >-
  Linus Norton, developer, tech lead and blogger
baseurl: ""
url: "https://ljn.io/"
lang: "en"
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-autoprefixer
  - jekyll-minifier
  - jekyll-youtube
  - jekyll-gist
exclude:
- README.md
- vendor/
- CNAME
- .idea/
- .git/
permalink: /posts/:title
excerpt_separator: <!--more-->
autoprefixer:
  browsers:
  - last 2 versions
sass:
  style: compressed
